# Cross Validation for IDW Interpolation 
## Task 2 (IDW for continuous data only)

This document includes Python codes that conduct cross validation (CV) for Inverse Distance Weighting (IDW) Interpolation on water quality parameters, including 6 water quality parameters in arcpy environment:
- Dissolved oxygen (DO_mgl)
- Salinity (Sal_ppt)
- Turbidity (Turb_ntu)
- Temperature (T_c)
- Secchi (Secc_m)
- Total Nitrogen (TN_mgl) 

The analysis is conducted in the separate water bodies:
- Guana Tolomato Matanzas (GTM)
- Estero Bay (EB)
- Charlotte Harbor (CH)
- Biscayne Bay (BB)
- Big Bend Seagrasses (BBS)

**Tasks:**  

- Task 2.1 Calculate the RMSE and Mean Error (ME) for IDW results using both continuous and discrete data.

- **Task 2.2 Calculate the RMSE and Mean Error (ME) for IDW results using continuous data.**

Time periods one year before and after storm event for Task 2A tests (seasons).
<br>
<div style="text-align: left;">
    <img src="misc/TimePeriods.png" style="display: block; margin-left: 0; margin-right: auto; width: 600px;"/>
</div>

Summary of IDW and RK Accuracy Assessments.
<br>
<div style="text-align: left;">
    <img src="misc/Table3.png" style="display: block; margin-left: 0; margin-right: auto; width: 600px;"/>
</div>

**Contents:**
* [1. Data Preprocess](#reg_preprocessing)
    * [1.1 Load csv files](#reg_subset)
    * [1.2 Subsetting data](#reg_preview)
    * [1.3 Define the wet and dry seasons](#reg_wetndry)
    * [1.4 Calculating average values](#reg_average)
    * [1.5 Convert coordinate system](#reg_coordinate)
* [2. Prepare for batch interpolation](#reg_batch)
    * [2.1 Preset abbreviation](#reg_preset)
    * [2.2 Define the barrier files](#reg_barrier)
    * [2.3 Define waterbody boundary](#reg_boundary)
    * [2.4 Load the table of study periods,  parameters, and seasons](#reg_study)
    * [2.5 Define output folders](#reg_output)
    * [2.6 Fill NaN RowID with unique ID](#reg_id)
* [3. Create Shapefiles](#reg_create_shp)
* [4. Cross Validation for IDW](#reg_cv_idw)

# 1. Loading packages

In [1]:
import pandas as pd
import numpy as np
import arcpy
from arcpy.sa import *
import os
import math

import importlib
import sys
# path = r'C:/Users/cong1/WQ/IDW/git/misc'
path = r'E:\Projects\SEACAR_WQ_2024\git\misc'

sys.path.insert(0, path)
import idw_rk
importlib.reload(idw_rk)

import pyproj

# define scratch folder to avoid overwritting from parallel threats
arcpy.env.scratchWorkspace = r"E:\Projects\SEACAR_WQ_2024\scratch/IDW_all"

## 1. Data Preprocessing <a class="anchor" id="reg_preprocessing"></a>

### 1.1 Load csv files

In [2]:
gis_path = r'E:\Projects\SEACAR_WQ_2024/GIS_Data/'
dfCon = pd.read_csv(gis_path + 'OEAT_Continuous_WQ-2024-Feb-21.csv', low_memory=False)

## 1.2 Subsetting Data <a class="anchor" id="reg_subset"></a>

### Selecting data from 9 am to 17 pm (daytime)

In [3]:
# Convert string to datetime
dfCon['SampleDate'] = pd.to_datetime(dfCon['SampleDate'], format='%Y-%m-%d %H:%M:%S.%f')

In [4]:
# Include date from 9:00 am to 17:00 pm
start_time = '09:00'
end_time = '17:00'

dfConTime = dfCon[dfCon['SampleDate'].dt.time.between(pd.to_datetime(start_time).time(), pd.to_datetime(end_time).time())]
dfConTime.head()

,RowID,ProgramID,ParameterName,ParameterUnits,ProgramLocationID,ActivityType,SampleDate,Year,Month,RelativeDepth,ResultValue,Latitude_DD,Longitude_DD,ManagedAreaName,AreaID,SEACAR_QAQCFlagCode,WaterBody,WbodyAcronym,Season
0,1,512,Water Temperature,Degrees C,CHWW1,NaN,2021-11-25 11:45:00,2021,11,bottom,19.2,26.8325,-82.14805,Cape Haze Aquatic Preserve,9,6Q,Charlotte Harbor,CH,Fall
1,2,512,Water Temperature,Degrees C,CHWW1,NaN,2021-11-13 16:15:00,2021,11,bottom,22.3,26.8325,-82.14805,Cape Haze Aquatic Preserve,9,6Q,Charlotte Harbor,CH,Fall
2,3,512,Water Temperature,Degrees C,CHWW1,NaN,2021-10-26 14:15:00,2021,10,bottom,28.3,26.8325,-82.14805,Cape Haze Aquatic Preserve,9,6Q,Charlotte Harbor,CH,Fall
3,4,512,Water Temperature,Degrees C,CHWW1,NaN,2022-09-16 12:45:00,2022,9,bottom,29.7,26.8325,-82.14805,Cape Haze Aquatic Preserve,9,6Q,Charlotte Harbor,CH,Fall
4,5,512,Water Temperature,Degrees C,CHWW1,NaN,2022-09-20 10:30:00,2022,9,bottom,29.3,26.8325,-82.14805,Cape Haze Aquatic Preserve,9,6Q,Charlotte Harbor,CH,Fall

### 1.3 Define the wet and dry seasons<a class="anchor" id="reg_wetndry"></a>

In [5]:
# Load the table of wet and dry seasons definitions
seasons2 = pd.read_csv(gis_path + '2 seasons.csv', low_memory=False)
seasons2

,WaterBody,Start Year,Start Month,Start Day,End Year,End Month,End Day,Start Date,End Date,Seasons
0,Charlotte Harbor,2017,5,1,2017,10,31,5/1/2017,10/31/2017,Wet
1,Charlotte Harbor,2017,11,1,2018,4,30,11/1/2017,4/30/2018,Dry
2,Big Bend Seagrasses,2021,5,1,2021,10,31,5/1/2021,10/31/2021,Wet
3,Big Bend Seagrasses,2021,11,1,2022,4,30,11/1/2021,4/30/2022,Dry
4,Estero Bay,2017,5,1,2017,10,31,5/1/2017,10/31/2017,Wet
5,Estero Bay,2017,11,1,2018,4,30,11/1/2017,4/30/2018,Dry
6,Guana Tolomato Matanzas,2016,5,1,2016,10,31,5/1/2016,10/31/2016,Wet
7,Guana Tolomato Matanzas,2016,11,1,2017,4,30,11/1/2016,4/30/2017,Dry
8,Biscayne Bay,2022,5,1,2022,10,31,5/1/2022,10/31/2022,Wet
9,Biscayne Bay,2022,11,1,2023,4,30,11/1/2022,4/30/2023,Dry

In [6]:
# Function to filters the year range
filtered_dfConTime = idw_rk.filter_data(dfConTime, seasons2)
filtered_dfConTime.head()

,RowID,ProgramID,ParameterName,ParameterUnits,ProgramLocationID,ActivityType,SampleDate,Year,Month,RelativeDepth,ResultValue,Latitude_DD,Longitude_DD,ManagedAreaName,AreaID,SEACAR_QAQCFlagCode,WaterBody,WbodyAcronym,Season
0,8701,471,Water Temperature,Degrees C,BBSST,NaN,2021-11-24 13:30:00,2021,11,bottom,15.9,29.647203,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall
1,8701,471,Water Temperature,Degrees C,BBSST,NaN,2021-11-24 13:30:00,2021,11,bottom,15.9,29.647203,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall
2,8702,471,Water Temperature,Degrees C,BBSST,NaN,2021-10-15 09:30:00,2021,10,bottom,27.0,29.647203,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall
3,8702,471,Water Temperature,Degrees C,BBSST,NaN,2021-10-15 09:30:00,2021,10,bottom,27.0,29.647203,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall
4,8703,471,Water Temperature,Degrees C,BBSST,NaN,2021-11-29 13:00:00,2021,11,bottom,15.7,29.647203,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall

In [7]:
# Assign wet and dry season
updated_dfConTime = idw_rk.assign_seasons(filtered_dfConTime, seasons2)
updated_dfConTime.head()

,RowID,ProgramID,ParameterName,ParameterUnits,ProgramLocationID,ActivityType,SampleDate,Year,Month,RelativeDepth,...,Longitude_DD,ManagedAreaName,AreaID,SEACAR_QAQCFlagCode,WaterBody,WbodyAcronym,Season,Start Date,End Date,Seasons
1,8701,471,Water Temperature,Degrees C,BBSST,NaN,2021-11-24 13:30:00,2021,11,bottom,...,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall,2021-11-01,2022-04-30,Dry
3,8701,471,Water Temperature,Degrees C,BBSST,NaN,2021-11-24 13:30:00,2021,11,bottom,...,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall,2021-11-01,2022-04-30,Dry
4,8702,471,Water Temperature,Degrees C,BBSST,NaN,2021-10-15 09:30:00,2021,10,bottom,...,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall,2021-05-01,2021-10-31,Wet
6,8702,471,Water Temperature,Degrees C,BBSST,NaN,2021-10-15 09:30:00,2021,10,bottom,...,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall,2021-05-01,2021-10-31,Wet
9,8703,471,Water Temperature,Degrees C,BBSST,NaN,2021-11-29 13:00:00,2021,11,bottom,...,-83.421196,Big Bend Seagrasses Aquatic Preserve,5,6Q,Big Bend Seagrasses,BBS,Fall,2021-11-01,2022-04-30,Dry

### 1.4 Calculating average values at unique observation points<a class="anchor" id="reg_average"></a>

In [8]:
dfCon_Mean = updated_dfConTime.groupby(['WaterBody','ParameterName','ParameterUnits', 'Year','Seasons','Latitude_DD','Longitude_DD','WbodyAcronym'])["ResultValue"].agg("mean").reset_index()
dfCon_Mean.head()

,WaterBody,ParameterName,ParameterUnits,Year,Seasons,Latitude_DD,Longitude_DD,WbodyAcronym,ResultValue
0,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2021,Dry,29.647203,-83.421196,BBS,7.382762
1,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2021,Wet,29.647203,-83.421196,BBS,5.017993
2,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2022,Dry,29.647203,-83.421196,BBS,7.503425
3,Big Bend Seagrasses,Salinity,ppt,2021,Dry,29.647203,-83.421196,BBS,29.472777
4,Big Bend Seagrasses,Salinity,ppt,2021,Wet,29.647203,-83.421196,BBS,25.350776

### 1.5 Convert coordinate system to EPSG: 3086<a class="anchor" id="reg_coordinate"></a>

In [9]:
# Define the EPSG codes for source (EPSG:4326) and target (EPSG:3086) coordinate systems
source_epsg = 'EPSG:4326'
target_epsg = 'EPSG:3086'

# Create a PyProj Transformer for the conversion
transformer = pyproj.Transformer.from_crs(source_epsg, target_epsg, always_xy=True)

# Define a function to apply the transformation to each row of the DataFrame
def transform_coordinates(row):
    x, y = transformer.transform(row['Longitude_DD'], row['Latitude_DD'])
    return pd.Series({'x': x, 'y': y})

# Apply the transformation function to the DataFrame and create new columns for the converted coordinates
dfCon_Mean[['x', 'y']] = dfCon_Mean.apply(transform_coordinates, axis=1)

## 2. Prepare for batch interpolation<a class="anchor" id="reg_batch"></a>
### 2.1 Preset abbreviation for waterbody and parameter name<a class="anchor" id="reg_preset"></a>

In [10]:
area_shortnames = {
    'Guana Tolomato Matanzas': 'GTM',
    'Estero Bay': 'EB',
    'Charlotte Harbor': 'CH',
    'Biscayne Bay': 'BB',
    'Big Bend Seagrasses':'BBS'
}

param_shortnames = {
    'Salinity': 'Sal_ppt',
    'Total Nitrogen': 'TN_mgl',
    'Dissolved Oxygen': 'DO_mgl',
    'Turbidity':'Turb_ntu',
    'Secchi Depth':'Secc_m',
    'Water Temperature':'T_c'
}

### 2.2 Define the barrier files<a class="anchor" id="reg_barrier"></a>

In [11]:
barrier_folder = os.path.join(gis_path, 'Barriers')
barrier_folder

barriers = []
for file in os.listdir(barrier_folder):
    if file.endswith(".shp"):
        barriers.append(os.path.join(barrier_folder, file))

for barrier in barriers:
    print(barrier)

E:\Projects\SEACAR_WQ_2024/GIS_Data/Barriers\BBS_Barriers.shp
E:\Projects\SEACAR_WQ_2024/GIS_Data/Barriers\BB_Barriers.shp
E:\Projects\SEACAR_WQ_2024/GIS_Data/Barriers\CH_Barriers.shp
E:\Projects\SEACAR_WQ_2024/GIS_Data/Barriers\EB_Barriers.shp
E:\Projects\SEACAR_WQ_2024/GIS_Data/Barriers\GTM_Barriers.shp

### 2.3 Define waterbody boundary for spatial extent and masking<a class="anchor" id="reg_boundary"></a>

In [12]:
waterbody_extent = os.path.join(gis_path, 'OEAT_Waterbody_Boundaries', 'OEAT_Waterbody_Boundary.shp')

unique_waterbodies = []
with arcpy.da.SearchCursor(waterbody_extent, ['WaterbodyA']) as cursor:
    for row in cursor:
        unique_waterbodies.append(row[0])

print("Unique Waterbodies:", unique_waterbodies)

Unique Waterbodies: ['BBS', 'BB', 'CH', 'EB', 'GTM']

### 2.4 Load the table of study periods,  parameters, and seasons<a class="anchor" id="reg_study"></a>

In [13]:
seasons_con = pd.read_csv(gis_path + 'WetDry_con.csv', low_memory=False)
seasons_con.head(10)

,WaterBody,Start Year,End Year,Seasons,Parameter,Filename,NumDataPoints,RMSE,ME
0,Charlotte Harbor,2017,2017,Wet,Salinity,NaN,NaN,NaN,NaN
1,Charlotte Harbor,2017,2018,Dry,Salinity,NaN,NaN,NaN,NaN
2,Big Bend Seagrasses,2021,2021,Wet,Salinity,NaN,NaN,NaN,NaN
3,Big Bend Seagrasses,2021,2022,Dry,Salinity,NaN,NaN,NaN,NaN
4,Estero Bay,2017,2017,Wet,Salinity,NaN,NaN,NaN,NaN
5,Estero Bay,2017,2018,Dry,Salinity,NaN,NaN,NaN,NaN
6,Guana Tolomato Matanzas,2016,2016,Wet,Salinity,NaN,NaN,NaN,NaN
7,Guana Tolomato Matanzas,2016,2017,Dry,Salinity,NaN,NaN,NaN,NaN
8,Biscayne Bay,2022,2022,Wet,Salinity,NaN,NaN,NaN,NaN
9,Biscayne Bay,2022,2023,Dry,Salinity,NaN,NaN,NaN,NaN

### 2.5 Define output folders

In [14]:
shpCon_folder = gis_path + r"shapefiles/shapefiles_Con"
idwCon_folder = gis_path + r"idw_Con"

# Preview data
dfCon_Mean

,WaterBody,ParameterName,ParameterUnits,Year,Seasons,Latitude_DD,Longitude_DD,WbodyAcronym,ResultValue,x,y
0,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2021,Dry,29.647203,-83.421196,BBS,7.382762,455952.502950,626846.023588
1,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2021,Wet,29.647203,-83.421196,BBS,5.017993,455952.502950,626846.023588
2,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2022,Dry,29.647203,-83.421196,BBS,7.503425,455952.502950,626846.023588
3,Big Bend Seagrasses,Salinity,ppt,2021,Dry,29.647203,-83.421196,BBS,29.472777,455952.502950,626846.023588
4,Big Bend Seagrasses,Salinity,ppt,2021,Wet,29.647203,-83.421196,BBS,25.350776,455952.502950,626846.023588
...,...,...,...,...,...,...,...,...,...,...,...
199,Guana Tolomato Matanzas,Water Temperature,Degrees C,2016,Wet,30.050857,-81.367465,GTM,28.690214,653510.005839,674232.563906
200,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,29.667071,-81.257403,GTM,22.574343,665054.640076,631868.177645
201,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,29.737041,-81.245953,GTM,21.343283,665987.547779,639659.183554
202,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,29.868851,-81.307428,GTM,21.544720,659731.716683,654157.848803
203,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,30.050857,-81.367465,GTM,21.936717,653510.005839,674232.563906

### 2.6 Fill NaN RowID with unique ID, IDW function needs unique ID <a class="anchor" id="reg_id"></a>

In [15]:
idw_rk.fill_nan_rowids(dfCon_Mean, 'RowID')
dfCon_Mean

,WaterBody,ParameterName,ParameterUnits,Year,Seasons,Latitude_DD,Longitude_DD,WbodyAcronym,ResultValue,x,y,RowID
0,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2021,Dry,29.647203,-83.421196,BBS,7.382762,455952.502950,626846.023588,1
1,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2021,Wet,29.647203,-83.421196,BBS,5.017993,455952.502950,626846.023588,2
2,Big Bend Seagrasses,Dissolved Oxygen,mg/L,2022,Dry,29.647203,-83.421196,BBS,7.503425,455952.502950,626846.023588,3
3,Big Bend Seagrasses,Salinity,ppt,2021,Dry,29.647203,-83.421196,BBS,29.472777,455952.502950,626846.023588,4
4,Big Bend Seagrasses,Salinity,ppt,2021,Wet,29.647203,-83.421196,BBS,25.350776,455952.502950,626846.023588,5
...,...,...,...,...,...,...,...,...,...,...,...,...
199,Guana Tolomato Matanzas,Water Temperature,Degrees C,2016,Wet,30.050857,-81.367465,GTM,28.690214,653510.005839,674232.563906,200
200,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,29.667071,-81.257403,GTM,22.574343,665054.640076,631868.177645,201
201,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,29.737041,-81.245953,GTM,21.343283,665987.547779,639659.183554,202
202,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,29.868851,-81.307428,GTM,21.544720,659731.716683,654157.848803,203
203,Guana Tolomato Matanzas,Water Temperature,Degrees C,2017,Dry,30.050857,-81.367465,GTM,21.936717,653510.005839,674232.563906,204

## 3. Create Shapefiles <a class="anchor" id="reg_create_shp">

In [16]:
# Empty the shapefile folder
idw_rk.delete_all_files(shpCon_folder)

# Merge interested with latitude and longitude columns
seasons_con_coord = idw_rk.merge_with_lat_long_wetdry(seasons_con, dfCon_Mean)
seasons_con_coord

,WaterBody,Start Year,End Year,Seasons,Parameter,Filename,NumDataPoints,RMSE,ME,Year,x,y,RowID,ResultValue
0,Charlotte Harbor,2017,2017,Wet,Salinity,NaN,NaN,NaN,NaN,2017,591885.252074,285703.675828,97,17.562691
1,Charlotte Harbor,2017,2017,Wet,Salinity,NaN,NaN,NaN,NaN,2017,592068.564186,293045.138022,98,17.137893
2,Charlotte Harbor,2017,2017,Wet,Salinity,NaN,NaN,NaN,NaN,2017,589298.655228,297332.015951,99,20.224163
3,Charlotte Harbor,2017,2018,Dry,Salinity,NaN,NaN,NaN,NaN,2017,591885.252074,285703.675828,94,13.909836
4,Charlotte Harbor,2017,2018,Dry,Salinity,NaN,NaN,NaN,NaN,2017,592068.564186,293045.138022,95,16.342843
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Biscayne Bay,2022,2023,Dry,Water Temperature,NaN,NaN,NaN,NaN,2023,782467.498344,202128.540268,80,25.151415
200,Biscayne Bay,2022,2023,Dry,Water Temperature,NaN,NaN,NaN,NaN,2023,780124.272070,202888.703873,81,25.414770
201,Biscayne Bay,2022,2023,Dry,Water Temperature,NaN,NaN,NaN,NaN,2023,785251.018719,207979.737666,82,25.002090
202,Biscayne Bay,2022,2023,Dry,Water Temperature,NaN,NaN,NaN,NaN,2023,784486.855104,208877.288889,83,25.011066
203,Biscayne Bay,2022,2023,Dry,Water Temperature,NaN,NaN,NaN,NaN,2023,782001.612166,210666.295536,84,25.245976

In [17]:
idw_rk.create_shp_seasons(seasons_con_coord, shpCon_folder)

Number of data rows for BBS, DO_mgl, 2021, Dry: 1
Shapefile for BBS: DO_mgl for year 2021 and season Dry has been saved as SHP_BBS_DO_mgl_Dry.shp
Number of data rows for BBS, Sal_ppt, 2021, Dry: 1
Shapefile for BBS: Sal_ppt for year 2021 and season Dry has been saved as SHP_BBS_Sal_ppt_Dry.shp
Number of data rows for BBS, Turb_ntu, 2021, Dry: 1
Shapefile for BBS: Turb_ntu for year 2021 and season Dry has been saved as SHP_BBS_Turb_ntu_Dry.shp
Number of data rows for BBS, T_c, 2021, Dry: 1
Shapefile for BBS: T_c for year 2021 and season Dry has been saved as SHP_BBS_T_c_Dry.shp
Number of data rows for BBS, DO_mgl, 2021, Wet: 1
Shapefile for BBS: DO_mgl for year 2021 and season Wet has been saved as SHP_BBS_DO_mgl_Wet.shp
Number of data rows for BBS, Sal_ppt, 2021, Wet: 1
Shapefile for BBS: Sal_ppt for year 2021 and season Wet has been saved as SHP_BBS_Sal_ppt_Wet.shp
Number of data rows for BBS, Turb_ntu, 2021, Wet: 1
Shapefile for BBS: Turb_ntu for year 2021 and season Wet has been saved as SHP_BBS_Turb_ntu_Wet.shp
Number of data rows for BBS, T_c, 2021, Wet: 1
Shapefile for BBS: T_c for year 2021 and season Wet has been saved as SHP_BBS_T_c_Wet.shp
Number of data rows for BBS, DO_mgl, 2022, Dry: 1
Shapefile for BBS: DO_mgl for year 2022 and season Dry has been saved as SHP_BBS_DO_mgl_Dry.shp
Number of data rows for BBS, Sal_ppt, 2022, Dry: 1
Shapefile for BBS: Sal_ppt for year 2022 and season Dry has been saved as SHP_BBS_Sal_ppt_Dry.shp
Number of data rows for BBS, Turb_ntu, 2022, Dry: 1
Shapefile for BBS: Turb_ntu for year 2022 and season Dry has been saved as SHP_BBS_Turb_ntu_Dry.shp
Number of data rows for BBS, T_c, 2022, Dry: 1
Shapefile for BBS: T_c for year 2022 and season Dry has been saved as SHP_BBS_T_c_Dry.shp
Number of data rows for BB, DO_mgl, 2022, Dry: 6
Shapefile for BB: DO_mgl for year 2022 and season Dry has been saved as SHP_BB_DO_mgl_Dry.shp
Number of data rows for BB, Sal_ppt, 2022, Dry: 6
Shapefile for BB: Sal_ppt for year 2022 and season Dry has been saved as SHP_BB_Sal_ppt_Dry.shp
Number of data rows for BB, Turb_ntu, 2022, Dry: 6
Shapefile for BB: Turb_ntu for year 2022 and season Dry has been saved as SHP_BB_Turb_ntu_Dry.shp
Number of data rows for BB, T_c, 2022, Dry: 6
Shapefile for BB: T_c for year 2022 and season Dry has been saved as SHP_BB_T_c_Dry.shp
Number of data rows for BB, DO_mgl, 2022, Wet: 6
Shapefile for BB: DO_mgl for year 2022 and season Wet has been saved as SHP_BB_DO_mgl_Wet.shp
Number of data rows for BB, Sal_ppt, 2022, Wet: 6
Shapefile for BB: Sal_ppt for year 2022 and season Wet has been saved as SHP_BB_Sal_ppt_Wet.shp
Number of data rows for BB, Turb_ntu, 2022, Wet: 6
Shapefile for BB: Turb_ntu for year 2022 and season Wet has been saved as SHP_BB_Turb_ntu_Wet.shp
Number of data rows for BB, T_c, 2022, Wet: 6
Shapefile for BB: T_c for year 2022 and season Wet has been saved as SHP_BB_T_c_Wet.shp
Number of data rows for BB, DO_mgl, 2023, Dry: 6
Shapefile for BB: DO_mgl for year 2023 and season Dry has been saved as SHP_BB_DO_mgl_Dry.shp
Number of data rows for BB, Sal_ppt, 2023, Dry: 6
Shapefile for BB: Sal_ppt for year 2023 and season Dry has been saved as SHP_BB_Sal_ppt_Dry.shp
Number of data rows for BB, Turb_ntu, 2023, Dry: 6
Shapefile for BB: Turb_ntu for year 2023 and season Dry has been saved as SHP_BB_Turb_ntu_Dry.shp
Number of data rows for BB, T_c, 2023, Dry: 6
Shapefile for BB: T_c for year 2023 and season Dry has been saved as SHP_BB_T_c_Dry.shp
Number of data rows for CH, DO_mgl, 2017, Dry: 3
Shapefile for CH: DO_mgl for year 2017 and season Dry has been saved as SHP_CH_DO_mgl_Dry.shp
Number of data rows for CH, Sal_ppt, 2017, Dry: 3
Shapefile for CH: Sal_ppt for year 2017 and season Dry has been saved as SHP_CH_Sal_ppt_Dry.shp
Number of data rows for CH, Turb_ntu, 2017, Dry: 3
Shapefile for CH: Turb_ntu for year 2017 and season Dry has been saved as SHP_CH_Turb_ntu_Dry.shp
Number of data rows for CH, T_c, 2017, Dry: 3
Shapefile for CH: T_c for year 2017 and season Dry has been saved as SHP_CH_T_c_Dry.shp
Number of data rows for CH, DO_mgl, 2017, Wet: 3
Shapefile for CH: DO_mgl for year 2017 and season Wet has been saved as SHP_CH_DO_mgl_Wet.shp
Number of data rows for CH, Sal_ppt, 2017, Wet: 3
Shapefile for CH: Sal_ppt for year 2017 and season Wet has been saved as SHP_CH_Sal_ppt_Wet.shp
Number of data rows for CH, Turb_ntu, 2017, Wet: 3
Shapefile for CH: Turb_ntu for year 2017 and season Wet has been saved as SHP_CH_Turb_ntu_Wet.shp
Number of data rows for CH, T_c, 2017, Wet: 3
Shapefile for CH: T_c for year 2017 and season Wet has been saved as SHP_CH_T_c_Wet.shp
Number of data rows for CH, DO_mgl, 2018, Dry: 3
Shapefile for CH: DO_mgl for year 2018 and season Dry has been saved as SHP_CH_DO_mgl_Dry.shp
Number of data rows for CH, Sal_ppt, 2018, Dry: 3
Shapefile for CH: Sal_ppt for year 2018 and season Dry has been saved as SHP_CH_Sal_ppt_Dry.shp
Number of data rows for CH, Turb_ntu, 2018, Dry: 3
Shapefile for CH: Turb_ntu for year 2018 and season Dry has been saved as SHP_CH_Turb_ntu_Dry.shp
Number of data rows for CH, T_c, 2018, Dry: 3
Shapefile for CH: T_c for year 2018 and season Dry has been saved as SHP_CH_T_c_Dry.shp
Number of data rows for EB, DO_mgl, 2017, Dry: 3
Shapefile for EB: DO_mgl for year 2017 and season Dry has been saved as SHP_EB_DO_mgl_Dry.shp
Number of data rows for EB, Sal_ppt, 2017, Dry: 3
Shapefile for EB: Sal_ppt for year 2017 and season Dry has been saved as SHP_EB_Sal_ppt_Dry.shp
Number of data rows for EB, Turb_ntu, 2017, Dry: 3
Shapefile for EB: Turb_ntu for year 2017 and season Dry has been saved as SHP_EB_Turb_ntu_Dry.shp
Number of data rows for EB, T_c, 2017, Dry: 3
Shapefile for EB: T_c for year 2017 and season Dry has been saved as SHP_EB_T_c_Dry.shp
Number of data rows for EB, DO_mgl, 2017, Wet: 3
Shapefile for EB: DO_mgl for year 2017 and season Wet has been saved as SHP_EB_DO_mgl_Wet.shp
Number of data rows for EB, Sal_ppt, 2017, Wet: 3
Shapefile for EB: Sal_ppt for year 2017 and season Wet has been saved as SHP_EB_Sal_ppt_Wet.shp
Number of data rows for EB, Turb_ntu, 2017, Wet: 3
Shapefile for EB: Turb_ntu for year 2017 and season Wet has been saved as SHP_EB_Turb_ntu_Wet.shp
Number of data rows for EB, T_c, 2017, Wet: 3
Shapefile for EB: T_c for year 2017 and season Wet has been saved as SHP_EB_T_c_Wet.shp
Number of data rows for EB, DO_mgl, 2018, Dry: 3
Shapefile for EB: DO_mgl for year 2018 and season Dry has been saved as SHP_EB_DO_mgl_Dry.shp
Number of data rows for EB, Sal_ppt, 2018, Dry: 3
Shapefile for EB: Sal_ppt for year 2018 and season Dry has been saved as SHP_EB_Sal_ppt_Dry.shp
Number of data rows for EB, Turb_ntu, 2018, Dry: 3
Shapefile for EB: Turb_ntu for year 2018 and season Dry has been saved as SHP_EB_Turb_ntu_Dry.shp
Number of data rows for EB, T_c, 2018, Dry: 3
Shapefile for EB: T_c for year 2018 and season Dry has been saved as SHP_EB_T_c_Dry.shp
Number of data rows for GTM, DO_mgl, 2016, Dry: 4
Shapefile for GTM: DO_mgl for year 2016 and season Dry has been saved as SHP_GTM_DO_mgl_Dry.shp
Number of data rows for GTM, Sal_ppt, 2016, Dry: 4
Shapefile for GTM: Sal_ppt for year 2016 and season Dry has been saved as SHP_GTM_Sal_ppt_Dry.shp
Number of data rows for GTM, Turb_ntu, 2016, Dry: 4
Shapefile for GTM: Turb_ntu for year 2016 and season Dry has been saved as SHP_GTM_Turb_ntu_Dry.shp
Number of data rows for GTM, T_c, 2016, Dry: 4
Shapefile for GTM: T_c for year 2016 and season Dry has been saved as SHP_GTM_T_c_Dry.shp
Number of data rows for GTM, DO_mgl, 2016, Wet: 4
Shapefile for GTM: DO_mgl for year 2016 and season Wet has been saved as SHP_GTM_DO_mgl_Wet.shp
Number of data rows for GTM, Sal_ppt, 2016, Wet: 4
Shapefile for GTM: Sal_ppt for year 2016 and season Wet has been saved as SHP_GTM_Sal_ppt_Wet.shp
Number of data rows for GTM, Turb_ntu, 2016, Wet: 4
Shapefile for GTM: Turb_ntu for year 2016 and season Wet has been saved as SHP_GTM_Turb_ntu_Wet.shp
Number of data rows for GTM, T_c, 2016, Wet: 4
Shapefile for GTM: T_c for year 2016 and season Wet has been saved as SHP_GTM_T_c_Wet.shp
Number of data rows for GTM, DO_mgl, 2017, Dry: 4
Shapefile for GTM: DO_mgl for year 2017 and season Dry has been saved as SHP_GTM_DO_mgl_Dry.shp
Number of data rows for GTM, Sal_ppt, 2017, Dry: 4

Shapefile for GTM: Sal_ppt for year 2017 and season Dry has been saved as SHP_GTM_Sal_ppt_Dry.shp
Number of data rows for GTM, Turb_ntu, 2017, Dry: 4
Shapefile for GTM: Turb_ntu for year 2017 and season Dry has been saved as SHP_GTM_Turb_ntu_Dry.shp
Number of data rows for GTM, T_c, 2017, Dry: 4
Shapefile for GTM: T_c for year 2017 and season Dry has been saved as SHP_GTM_T_c_Dry.shp

## 4. Cross Validation for IDW <a class="anchor" id="reg_cv_idw"></a>

In [18]:
# Empty the shapefile folder
idw_rk.delete_all_files(idwCon_folder)

In [19]:
# Select a section of table to process
seasons_slct = seasons_con.iloc[:]

In [21]:
# If the number of data points is less than 3，skipping calculate IDW
idw_rk.idw_interpolation_wetdry(seasons_con, shpCon_folder, idwCon_folder, waterbody_extent, barrier_folder)

Processing file: SHP_CH_Sal_ppt_Wet.shp
File SHP_CH_Sal_ppt_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_CH_Sal_ppt_Dry.shp
File SHP_CH_Sal_ppt_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_BBS_Sal_ppt_Wet.shp
Not enough data for IDW interpolation in SHP_BBS_Sal_ppt_Wet.shp, skipping
Processing file: SHP_BBS_Sal_ppt_Dry.shp
Not enough data for IDW interpolation in SHP_BBS_Sal_ppt_Dry.shp, skipping
Processing file: SHP_EB_Sal_ppt_Wet.shp
File SHP_EB_Sal_ppt_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_EB_Sal_ppt_Dry.shp
File SHP_EB_Sal_ppt_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_GTM_Sal_ppt_Wet.shp
File SHP_GTM_Sal_ppt_Wet.shp has completed 4 cross-validation iterations.
Processing file: SHP_GTM_Sal_ppt_Dry.shp
File SHP_GTM_Sal_ppt_Dry.shp has completed 4 cross-validation iterations.
Processing file: SHP_BB_Sal_ppt_Wet.shp
File SHP_BB_Sal_ppt_Wet.shp has completed 6 cross-validation iterations.
Processing file: SHP_BB_Sal_ppt_Dry.shp
File SHP_BB_Sal_ppt_Dry.shp has completed 6 cross-validation iterations.
Processing file: SHP_CH_DO_mgl_Wet.shp
File SHP_CH_DO_mgl_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_CH_DO_mgl_Dry.shp
File SHP_CH_DO_mgl_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_BBS_DO_mgl_Wet.shp
Not enough data for IDW interpolation in SHP_BBS_DO_mgl_Wet.shp, skipping
Processing file: SHP_BBS_DO_mgl_Dry.shp
Not enough data for IDW interpolation in SHP_BBS_DO_mgl_Dry.shp, skipping
Processing file: SHP_EB_DO_mgl_Wet.shp
File SHP_EB_DO_mgl_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_EB_DO_mgl_Dry.shp
File SHP_EB_DO_mgl_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_GTM_DO_mgl_Wet.shp
File SHP_GTM_DO_mgl_Wet.shp has completed 4 cross-validation iterations.
Processing file: SHP_GTM_DO_mgl_Dry.shp
File SHP_GTM_DO_mgl_Dry.shp has completed 4 cross-validation iterations.
Processing file: SHP_BB_DO_mgl_Wet.shp
File SHP_BB_DO_mgl_Wet.shp has completed 6 cross-validation iterations.
Processing file: SHP_BB_DO_mgl_Dry.shp
File SHP_BB_DO_mgl_Dry.shp has completed 6 cross-validation iterations.
Processing file: SHP_CH_Turb_ntu_Wet.shp
File SHP_CH_Turb_ntu_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_CH_Turb_ntu_Dry.shp
File SHP_CH_Turb_ntu_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_BBS_Turb_ntu_Wet.shp
Not enough data for IDW interpolation in SHP_BBS_Turb_ntu_Wet.shp, skipping
Processing file: SHP_BBS_Turb_ntu_Dry.shp
Not enough data for IDW interpolation in SHP_BBS_Turb_ntu_Dry.shp, skipping
Processing file: SHP_EB_Turb_ntu_Wet.shp
File SHP_EB_Turb_ntu_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_EB_Turb_ntu_Dry.shp
File SHP_EB_Turb_ntu_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_GTM_Turb_ntu_Wet.shp
File SHP_GTM_Turb_ntu_Wet.shp has completed 4 cross-validation iterations.
Processing file: SHP_GTM_Turb_ntu_Dry.shp
File SHP_GTM_Turb_ntu_Dry.shp has completed 4 cross-validation iterations.
Processing file: SHP_BB_Turb_ntu_Wet.shp
File SHP_BB_Turb_ntu_Wet.shp has completed 6 cross-validation iterations.
Processing file: SHP_BB_Turb_ntu_Dry.shp
File SHP_BB_Turb_ntu_Dry.shp has completed 6 cross-validation iterations.
Processing file: SHP_CH_T_c_Wet.shp
File SHP_CH_T_c_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_CH_T_c_Dry.shp
File SHP_CH_T_c_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_BBS_T_c_Wet.shp
Not enough data for IDW interpolation in SHP_BBS_T_c_Wet.shp, skipping
Processing file: SHP_BBS_T_c_Dry.shp
Not enough data for IDW interpolation in SHP_BBS_T_c_Dry.shp, skipping
Processing file: SHP_EB_T_c_Wet.shp
File SHP_EB_T_c_Wet.shp has completed 3 cross-validation iterations.
Processing file: SHP_EB_T_c_Dry.shp
File SHP_EB_T_c_Dry.shp has completed 3 cross-validation iterations.
Processing file: SHP_GTM_T_c_Wet.shp
File SHP_GTM_T_c_Wet.shp has completed 4 cross-validation iterations.
Processing file: SHP_GTM_T_c_Dry.shp
File SHP_GTM_T_c_Dry.shp has completed 4 cross-validation iterations.
Processing file: SHP_BB_T_c_Wet.shp
File SHP_BB_T_c_Wet.shp has completed 6 cross-validation iterations.
Processing file: SHP_BB_T_c_Dry.shp
File SHP_BB_T_c_Dry.shp has completed 6 cross-validation iterations.
Calculated RMSE: 0.047464286959605535, ME: 0.008614799600001 for file: SHP_BB_T_c_Dry.shp. Time used: 314.7526869773865